---
- hosts: all
  become: true
  tasks:
    - name: Httpd installed
      yum:
        name: httpd
        state: latest
    - name: start the service
      service:
        name: httpd
        state: started
        enabled: yes
